apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: teu-user/simulador-api:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: volume
              mountPath: /app/volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: minio-pvc
