apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
        - name: sensor
          image: teu-user/simulador-sensor:latest
