name: Build, Push API Docker Image and Deploy to Kubernetes

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/build-api.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/simulador-api:latest ./api
          docker push ghcr.io/${{ github.repository }}/simulador-api:latest

      - name: Set up Kubeconfig
        uses: azure/setup-kubeconfig@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/simulador-api-deployment.yaml
          kubectl set image deployment/simulador-api simulador-api=ghcr.io/${{ github.repository }}/simulador-api:latest
