name: Build and Push API Docker Image

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/build-api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: speedfick
          password: ${{ secrets.PAT_GHCR }}

      - name: Build Docker image
        run: docker build -t ghcr.io/speedfick/simulador-api:latest ./api

      - name: Push Docker image
        run: docker push ghcr.io/speedfick/simulador-api:latest

      - name: Logout from Docker Hub
        run: docker logout