name: Build and Push Website Docker Image

on:
  push:
    paths:
      - 'website/**'
      - '.github/workflows/build-website.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # Usando o nome do usuário do GitHub
          password: ${{ secrets.GITHUB_TOKEN }}  # O token GITHUB_TOKEN

      - name: Build Docker image
        run: docker build -t ghcr.io/speedfick/simulador-website:latest ./website  # Usando o GHCR como destino

      - name: Push Docker image
        run: docker push ghcr.io/speedfick/simulador-website:latest  # Empurrando para o GHCR
